In [1]:
import pandas as pd
import geopandas as pgd
import numpy as np
import os

In [2]:
os.chdir(r'C:\Users\laugi\OneDrive_backup\3\OneDrive\Doctorado\3_PGS\Valencia\Rain')

In [3]:
os.listdir()

['1990_01_rr.tif',
 '1990_02_rr.tif',
 '1990_03_rr.tif',
 '1990_04_rr.tif',
 '1990_05_rr.tif',
 '1990_06_rr.tif',
 '1990_07_rr.tif',
 '1990_08_rr.tif',
 '1990_09_rr.tif',
 '1990_10_rr.tif',
 '1990_11_rr.tif',
 '1990_12_rr.tif',
 '1991_01_rr.tif',
 '1991_02_rr.tif',
 '1991_03_rr.tif',
 '1991_04_rr.tif',
 '1991_05_rr.tif',
 '1991_06_rr.tif',
 '1991_07_rr.tif',
 '1991_08_rr.tif',
 '1991_09_rr.tif',
 '1991_10_rr.tif',
 '1991_11_rr.tif',
 '1991_12_rr.tif',
 '1992_01_rr.tif',
 '1992_02_rr.tif',
 '1992_03_rr.tif',
 '1992_04_rr.tif',
 '1992_05_rr.tif',
 '1992_06_rr.tif',
 '1992_07_rr.tif',
 '1992_08_rr.tif',
 '1992_09_rr.tif',
 '1992_10_rr.tif',
 '1992_11_rr.tif',
 '1992_12_rr.tif',
 '1993_01_rr.tif',
 '1993_02_rr.tif',
 '1993_03_rr.tif',
 '1993_04_rr.tif',
 '1993_05_rr.tif',
 '1993_06_rr.tif',
 '1993_07_rr.tif',
 '1993_08_rr.tif',
 '1993_09_rr.tif',
 '1993_10_rr.tif',
 '1993_11_rr.tif',
 '1993_12_rr.tif',
 '1994_01_rr.tif',
 '1994_02_rr.tif',
 '1994_03_rr.tif',
 '1994_04_rr.tif',
 '1994_05_rr.tif',
 '1994_06_rr.tif',
 '1994_07_rr.tif',
 '1994_08_rr.tif',
 '1994_09_rr.tif',
 '1994_10_rr.tif',
 '1994_11_rr.tif',
 '1994_12_rr.tif',
 '1995_01_rr.tif',
 '1995_02_rr.tif',
 '1995_03_rr.tif',
 '1995_04_rr.tif',
 '1995_05_rr.tif',
 '1995_06_rr.tif',
 '1995_07_rr.tif',
 '1995_08_rr.tif',
 '1995_09_rr.tif',
 '1995_10_rr.tif',
 '1995_11_rr.tif',
 '1995_12_rr.tif',
 '1996_01_rr.tif',
 '1996_02_rr.tif',
 '1996_03_rr.tif',
 '1996_04_rr.tif',
 '1996_05_rr.tif',
 '1996_06_rr.tif',
 '1996_07_rr.tif',
 '1996_08_rr.tif',
 '1996_09_rr.tif',
 '1996_10_rr.tif',
 '1996_11_rr.tif',
 '1996_12_rr.tif',
 '1997_01_rr.tif',
 '1997_02_rr.tif',
 '1997_03_rr.tif',
 '1997_04_rr.tif',
 '1997_05_rr.tif',
 '1997_06_rr.tif',
 '1997_07_rr.tif',
 '1997_08_rr.tif',
 '1997_09_rr.tif',
 '1997_10_rr.tif',
 '1997_11_rr.tif',
 '1997_12_rr.tif',
 '1998_01_rr.tif',
 '1998_02_rr.tif',
 '1998_03_rr.tif',
 '1998_04_rr.tif',
 '1998_05_rr.tif',
 '1998_06_rr.tif',
 '1998_07_rr.tif',
 '1998_08_rr.tif',
 '1998_09_rr.tif',
 '1998_10_rr.tif',
 '1998_11_rr.tif',
 '1998_12_rr.tif',
 '1999_01_rr.tif',
 '1999_02_rr.tif',
 '1999_03_rr.tif',
 '1999_04_rr.tif',
 '1999_05_rr.tif',
 '1999_06_rr.tif',
 '1999_07_rr.tif',
 '1999_08_rr.tif',
 '1999_09_rr.tif',
 '1999_10_rr.tif',
 '1999_11_rr.tif',
 '1999_12_rr.tif',
 '2000_01_rr.tif',
 '2000_02_rr.tif',
 '2000_03_rr.tif',
 '2000_04_rr.tif',
 '2000_05_rr.tif',
 '2000_06_rr.tif',
 '2000_07_rr.tif',
 '2000_08_rr.tif',
 '2000_09_rr.tif',
 '2000_10_rr.tif',
 '2000_11_rr.tif',
 '2000_12_rr.tif',
 '2001_01_rr.tif',
 '2001_02_rr.tif',
 '2001_03_rr.tif',
 '2001_04_rr.tif',
 '2001_05_rr.tif',
 '2001_06_rr.tif',
 '2001_07_rr.tif',
 '2001_08_rr.tif',
 '2001_09_rr.tif',
 '2001_10_rr.tif',
 '2001_11_rr.tif',
 '2001_12_rr.tif',
 '2002_01_rr.tif',
 '2002_02_rr.tif',
 '2002_03_rr.tif',
 '2002_04_rr.tif',
 '2002_05_rr.tif',
 '2002_06_rr.tif',
 '2002_07_rr.tif',
 '2002_08_rr.tif',
 '2002_09_rr.tif',
 '2002_10_rr.tif',
 '2002_11_rr.tif',
 '2002_12_rr.tif',
 '2003_01_rr.tif',
 '2003_02_rr.tif',
 '2003_03_rr.tif',
 '2003_04_rr.tif',
 '2003_05_rr.tif',
 '2003_06_rr.tif',
 '2003_07_rr.tif',
 '2003_08_rr.tif',
 '2003_09_rr.tif',
 '2003_10_rr.tif',
 '2003_11_rr.tif',
 '2003_12_rr.tif',
 '2004_01_rr.tif',
 '2004_02_rr.tif',
 '2004_03_rr.tif',
 '2004_04_rr.tif',
 '2004_05_rr.tif',
 '2004_06_rr.tif',
 '2004_07_rr.tif',
 '2004_08_rr.tif',
 '2004_09_rr.tif',
 '2004_10_rr.tif',
 '2004_11_rr.tif',
 '2004_12_rr.tif',
 '2005_01_rr.tif',
 '2005_02_rr.tif',
 '2005_03_rr.tif',
 '2005_04_rr.tif',
 '2005_05_rr.tif',
 '2005_06_rr.tif',
 '2005_07_rr.tif',
 '2005_08_rr.tif',
 '2005_09_rr.tif',
 '2005_10_rr.tif',
 '2005_11_rr.tif',
 '2005_12_rr.tif',
 '2006_01_rr.tif',
 '2006_02_rr.tif',
 '2006_03_rr.tif',
 '2006_04_rr.tif',
 '2006_05_rr.tif',
 '2006_06_rr.tif',
 '2006_07_rr.tif',
 '2006_08_rr.tif',
 '2006_09_rr.tif',
 '2006_10_rr.tif',
 '2006_11_rr.tif',
 '2006_12_rr.tif',
 '2007_01_rr.tif',
 '2007_02_rr.tif',
 '2007_03_rr.tif',
 '2007_04_rr.tif',
 '2007_05_rr.tif',
 '2007_06_rr.tif',
 '2007_07_rr.tif',
 '2007_08_rr.tif',
 '2007_09_rr.tif',
 '2007_10_rr.tif',
 '2007_11_rr.tif',
 '2007_12_rr.tif',
 '2008_01_rr.tif',
 '2008_02_rr.tif',
 '2008_03_rr.tif',
 '2008_04_rr.tif',
 '2008_05_rr.tif',
 '2008_06_rr.tif',
 '2008_07_rr.tif',
 '2008_08_rr.tif',
 '2008_09_rr.tif',
 '2008_10_rr.tif',
 '2008_11_rr.tif',
 '2008_12_rr.tif',
 '2009_01_rr.tif',
 '2009_02_rr.tif',
 '2009_03_rr.tif',
 '2009_04_rr.tif',
 '2009_05_rr.tif',
 '2009_06_rr.tif',
 '2009_07_rr.tif',
 '2009_08_rr.tif',
 '2009_09_rr.tif',
 '2009_10_rr.tif',
 '2009_11_rr.tif',
 '2009_12_rr.tif',
 '2010_01_rr.tif',
 '2010_02_rr.tif',
 '2010_03_rr.tif',
 '2010_04_rr.tif',
 '2010_05_rr.tif',
 '2010_06_rr.tif',
 '2010_07_rr.tif',
 '2010_08_rr.tif',
 '2010_09_rr.tif',
 '2010_10_rr.tif',
 '2010_11_rr.tif',
 '2010_12_rr.tif',
 '2011_01_rr.tif',
 '2011_02_rr.tif',
 '2011_03_rr.tif',
 '2011_04_rr.tif',
 '2011_05_rr.tif',
 '2011_06_rr.tif',
 '2011_07_rr.tif',
 '2011_08_rr.tif',
 '2011_09_rr.tif',
 '2011_10_rr.tif',
 '2011_11_rr.tif',
 '2011_12_rr.tif',
 '2012_01_rr.tif',
 '2012_02_rr.tif',
 '2012_03_rr.tif',
 '2012_04_rr.tif',
 '2012_05_rr.tif',
 '2012_06_rr.tif',
 '2012_07_rr.tif',
 '2012_08_rr.tif',
 '2012_09_rr.tif',
 '2012_10_rr.tif',
 '2012_11_rr.tif',
 '2012_12_rr.tif',
 '2013_01_rr.tif',
 '2013_02_rr.tif',
 '2013_03_rr.tif',
 '2013_04_rr.tif',
 '2013_05_rr.tif',
 '2013_06_rr.tif',
 '2013_07_rr.tif',
 '2013_08_rr.tif',
 '2013_09_rr.tif',
 '2013_10_rr.tif',
 '2013_11_rr.tif',
 '2013_12_rr.tif',
 '2014_01_rr.tif',
 '2014_02_rr.tif',
 '2014_03_rr.tif',
 '2014_04_rr.tif',
 '2014_05_rr.tif',
 '2014_06_rr.tif',
 '2014_07_rr.tif',
 '2014_08_rr.tif',
 '2014_09_rr.tif',
 '2014_10_rr.tif',
 '2014_11_rr.tif',
 '2014_12_rr.tif',
 '2015_01_rr.tif',
 '2015_02_rr.tif',
 '2015_03_rr.tif',
 '2015_04_rr.tif',
 '2015_05_rr.tif',
 '2015_06_rr.tif',
 '2015_07_rr.tif',
 '2015_08_rr.tif',
 '2015_09_rr.tif',
 '2015_10_rr.tif',
 '2015_11_rr.tif',
 '2015_12_rr.tif',
 '2016_01_rr.tif',
 '2016_02_rr.tif',
 '2016_03_rr.tif',
 '2016_04_rr.tif',
 '2016_05_rr.tif',
 '2016_06_rr.tif',
 '2016_07_rr.tif',
 '2016_08_rr.tif',
 '2016_09_rr.tif',
 '2016_10_rr.tif',
 '2016_11_rr.tif',
 '2016_12_rr.tif',
 '2017_01_rr.tif',
 '2017_02_rr.tif',
 '2017_03_rr.tif',
 '2017_04_rr.tif',
 '2017_05_rr.tif',
 '2017_06_rr.tif',
 '2017_07_rr.tif',
 '2017_08_rr.tif',
 '2017_09_rr.tif',
 '2017_10_rr.tif',
 '2017_11_rr.tif',
 '2017_12_rr.tif',
 '2018_01_rr.tif',
 '2018_02_rr.tif',
 '2018_03_rr.tif',
 '2018_04_rr.tif',
 '2018_05_rr.tif',
 '2018_06_rr.tif',
 '2018_07_rr.tif',
 '2018_08_rr.tif',
 '2018_09_rr.tif',
 '2018_10_rr.tif',
 '2018_11_rr.tif',
 '2018_12_rr.tif',
 '2019_01_rr.tif',
 '2019_02_rr.tif',
 '2019_03_rr.tif',
 '2019_04_rr.tif',
 '2019_05_rr.tif',
 '2019_06_rr.tif',
 '2019_07_rr.tif',
 '2019_08_rr.tif',
 '2019_09_rr.tif',
 '2019_10_rr.tif',
 '2019_11_rr.tif',
 '2019_12_rr.tif',
 '2020_01_rr.tif',
 '2020_02_rr.tif',
 '2020_03_rr.tif',
 '2020_04_rr.tif',
 '2020_05_rr.tif',
 '2020_06_rr.tif',
 '2020_07_rr.tif',
 '2020_08_rr.tif',
 '2020_09_rr.tif',
 '2020_10_rr.tif',
 '2020_11_rr.tif',
 '2020_12_rr.tif',
 '2021_01_rr.tif',
 '2021_02_rr.tif',
 '2021_03_rr.tif',
 '2021_04_rr.tif',
 '2021_05_rr.tif',
 '2021_06_rr.tif',
 '2021_07_rr.tif',
 '2021_08_rr.tif',
 '2021_09_rr.tif',
 '2021_10_rr.tif',
 '2021_11_rr.tif',
 '2021_12_rr.tif',
 '2022_01_rr.tif',
 '2022_02_rr.tif',
 '2022_03_rr.tif',
 '2022_04_rr.tif',
 '2022_05_rr.tif',
 '2022_06_rr.tif',
 '2022_07_rr.tif',
 '2022_08_rr.tif',
 '2022_09_rr.tif',
 '2022_10_rr.tif',
 '2022_11_rr.tif',
 '2022_12_rr.tif',
 '2023_01_rr.tif',
 '2023_02_rr.tif',
 '2023_03_rr.tif',
 '2023_04_rr.tif',
 '2023_05_rr.tif',
 '2023_06_rr.tif',
 '2023_07_rr.tif',
 '2023_08_rr.tif',
 '2023_09_rr.tif',
 '2023_10_rr.tif',
 '2023_11_rr.tif',
 '2023_12_rr.tif',
 'Valencia_prec.csv']

In [5]:
# df = pd.read_csv('Navarra_Tmin.csv', dtype={'Row': str, 'Prec': float, 'Date': str})
# df = pd.read_csv('Valencia_prec.csv', dtype={'Row': str, 'Prec': float, 'Date': str})

In [6]:
df = pd.read_csv('Valencia_prec.csv', usecols=['Date', 'Row', 'Prec'])

In [ ]:
df

In [12]:
# os.chdir('C:\\Users\\agiambel.stu\\OneDrive\\Doctorado\\3_PGS\\3PGS\\Tmin')
# os.chdir('C:\\Users\\agiambel.stu\\OneDrive\\Doctorado\\3_PGS\\Valencia\\Rain')
# os.chdir('E:\\Catalunia_s_int\\Rain')

# os.listdir()

In [34]:
df=df[['Date', 'Latitude', 'Longitude', 'Row', 'Prec', 'row','column']]
# Cat_tx.columns=['Date', 'Latitude', 'Longitude', 'Row', 'Tmax', 'row','column']

In [8]:
# puntos=pd.read_csv('C:\\Users\\giambelluca.144055\\OneDrive\\Doctorado\\Datos Estancia\\Incendios_estancia\\Filtrados\\Usar_NBR\\Filter_R_Valencia_011124.csv')
puntos=pd.read_csv('C:\\Users\\laugi\\OneDrive_backup\\3\\OneDrive\\Doctorado\\Datos Estancia\\Incendios_estancia\\Filtrados\\Usar_NBR\\Filter_R_Valencia_011124.csv')
puntos=puntos[['Row','FECHA']]
variable=pd.merge(df,puntos,on='Row')
len(variable)

6338280

In [9]:
def fechas(num):
    return str(num)[:7]
variable['Date']=variable['Date'].apply(fechas)

def year(num):
    return str(num)[:4]

def month(num):
    return str(num)[5:]

variable['Year']=variable['Date'].apply(year)
variable['Month']=variable['Date'].apply(month)
variable

            Date          Row       Prec  FECHA  Year Month
0        1990_01  [6303 5358]  67.800003   1993  1990    01
1        1990_02  [6303 5358]   0.000000   1993  1990    02
2        1990_03  [6303 5358]  12.800000   1993  1990    03
3        1990_04  [6303 5358]  40.900002   1993  1990    04
4        1990_05  [6303 5358]  35.299999   1993  1990    05
...          ...          ...        ...    ...   ...   ...
6338275  2023_08  [8856 5649]   0.000000   2003  2023    08
6338276  2023_09  [8856 5649]  94.900002   2003  2023    09
6338277  2023_10  [8856 5649]   4.600000   2003  2023    10
6338278  2023_11  [8856 5649]   0.000000   2003  2023    11
6338279  2023_12  [8856 5649]   2.600000   2003  2023    12

[6338280 rows x 6 columns]

In [10]:
variable=variable.loc[(variable.Month=='05')|(variable.Month=='06')|(variable.Month=='07')|(variable.Month=='08')|(variable.Month=='09')|(variable.Month=='10')]

In [11]:
join=variable
join['Year']=join['Year'].astype(int)
join['FECHA']=join['FECHA'].astype(int)

C:\Users\laugi\AppData\Local\Temp\ipykernel_10444\3116722360.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  join['Year']=join['Year'].astype(int)
C:\Users\laugi\AppData\Local\Temp\ipykernel_10444\3116722360.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  join['FECHA']=join['FECHA'].astype(int)

In [12]:
filtered_5year=join.loc[((join.Year>=(join.FECHA))&(join.Year<(join.FECHA+5)))]
filtered_20year=join.loc[(join.Year>=(join.FECHA))&(join.Year<(join.FECHA+20))]

In [13]:
resultados_V_5 = filtered_5year.groupby('Row')['Prec'].sum().reset_index()
resultados_V_5.columns=['Row','Prec_5']
resultados_V_20 = filtered_20year.groupby('Row')['Prec'].sum().reset_index()
resultados_V_20.columns=['Row','Prec_20']

In [14]:
join_v=pd.merge(resultados_V_5,resultados_V_20,on='Row')
join_v

               Row       Prec_5      Prec_20
0      [ 788 6834]  1143.800045  4269.800100
1      [ 790 6830]  1143.800045  4269.800100
2      [ 792 6826]  1143.800045  4269.800100
3      [ 806 6819]  1143.800045  4269.800100
4      [ 808 6823]  1143.800045  4269.800100
...            ...          ...          ...
15530  [9228 5349]   777.000028  2682.100040
15531  [9595 3801]   617.800004  2306.800039
15532  [9597 3805]   617.800004  2306.800039
15533  [9655 3829]   572.400001  2509.100016
15534  [9887 3762]   532.399997  2476.900015

[15535 rows x 3 columns]

In [16]:
join_v.Prec_20.min()

1964.6000266075134

In [45]:
join=pd.merge(join_v,Tmin,on='Row')

In [46]:
join_v=pd.merge(join,Tmax,on='Row')

In [ ]:
join_v

In [18]:
os.chdir('C:\\Users\\laugi\\OneDrive_backup\\3\\OneDrive\\Incendios\\Clima\\5y20')

In [19]:
join_v.to_csv('Valencia_prec_5y20.csv')

In [16]:
Tmin=join_v

In [29]:
Tmax=join_v

# Comparacion

In [16]:
os.chdir('C:\\Users\\giambelluca.144055\\OneDrive\\Incendios\\Organizacion\\Resultados\\Clima\\Valencia')
tmin=pd.read_csv('Valencia_after_and_before_prec.csv')

In [17]:
tmin.columns=['Unnamed: 0', 'Row', 'Tmin_1', 'Tmin_5_COMPARAMOS', 'Tmin_10', 'Tmin_b']

In [ ]:
todo=pd.merge(tmin,join_v,on='Row')
todo=todo[['Tmin_1', 'Tmin_5_COMPARAMOS', 'Tmin_10', 'Tmin_b','Prec_5', 'Prec_20']]
todo.corr()

In [ ]:
todo.columns